[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify函数配置
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "pnpm dev"
  port = 3000
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API路由重定向到Netlify函数
[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/api/task-status"
  to = "/.netlify/functions/task-status"
  status = 200

# 其他API路由使用Next.js处理
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
